# version: "3.9"
services:
  ctp:
    image: parasoft/ctp:latest
    restart: unless-stopped
    hostname: ctp
    container_name: ctp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
<<<<<<< HEAD
      - 8080:8080
      - 8443:8443
      - 9009:9002
=======
      - 8080:8080 # HTTP
      - 8443:8443 # HTTPS
      - 9009:9002 # HSQLDB
>>>>>>> 21c951f (updates)
    environment:
      ACCEPT_EULA: true
      LICENSE_SERVER_URL: "${ls_url}"
      LICENSE_SERVER_AUTH_ENABLED: true
      LICENSE_SERVER_USERNAME: "${ls_user}"
      LICENSE_SERVER_PASSWORD: "${ls_pass}"
      USAGE_DATA: false      
      #CATALINA_OPTS: "-Djavax.net.debug=ssl:handshake"
    volumes:
      - type: bind
        source: ctp/hsqldb
        target: /usr/local/parasoft/ctp/hsqldb
      - type: bind
        source: ctp/exports
        target: /usr/local/parasoft/exports
      - type: bind
        source: ctp/PSTSecConfig.xml
        target: /usr/local/parasoft/ctp/webapps/em/config/PSTSecConfig.xml
  soavirt-server:
    image: parasoft/soavirt-server:latest
    restart: unless-stopped
    container_name: soavirt-server
    hostname: soavirt-server
    depends_on:
      - ctp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
<<<<<<< HEAD
      - 9080:9080
      - 9443:9443
      - 9617:9617
      - 9618:9618
      - 9090-9099:9090-9099
=======
      - 9080:9080 # HTTP
      - 9443:9443 # HTTPS
      - 9617:9617 # Events Monitoring
      - 9618:9618 # Hit Statistics
      - 9090-9099:9090-9099 # Custom listeners
>>>>>>> 21c951f (updates)
    environment:
      ACCEPT_EULA: "true"
      HTTP_PORT: 9080
      EVENTS_PORT: 9617
      STATISTICS_PORT: 9618
    env_file:
      - ./soavirt/catalina.env
    volumes:
      - type: bind
        source: soavirt/workspace
        target: /usr/local/parasoft/soavirt/webapps/ROOT/workspace
      - type: bind
        source: soavirt/config.properties
        target: /usr/local/parasoft/soavirt/webapps/ROOT/WEB-INF/config.properties
  datarepo:
    image: parasoft/datarepo:latest
    restart: unless-stopped
    container_name: datarepo
    hostname: datarepo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
      - "2424:2424" # TCP
    environment:
      USERNAME: ${dr_user}
      PASSWORD: ${dr_pass}
      CTP_URL: ${ctp_url}
      CTP_USERNAME: ${ctp_user}
      CTP_PASSWORD: ${ctp_pass}
      ALIAS: ${dr_alias}
    volumes:
      - type: bind
        source: datarepo/repositories
        target: /usr/local/parasoft/datarepo/repositories
  parabank:
    build: parabank
    restart: unless-stopped
    container_name: parabank
    hostname: parabank
    user: 0:0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
      - 8090:8080 # HTTP
      - 9001:9001 # HSQLDB
      - 61616:61616 # JMS
      - 8050:8050 # Cov Agent
    env_file:
      - ./parabank/catalina.env
    volumes:
      - type: bind
        source: parabank/jdbc/jdbc.properties
        target: /usr/local/tomcat/webapps/parabank/WEB-INF/classes/jdbc.properties
      - type: bind
        source: parabank/jdbc/ParasoftJDBCDriver.jar
        target: /usr/local/tomcat/webapps/parabank/WEB-INF/lib/ParasoftJDBCDriver.jar
      - type: bind
        source: parabank/agent/runtime_coverage
        target: /usr/local/tomcat/agent/runtime_coverage
  parabankv2:
    image: parasoft/parabank:feature
    restart: unless-stopped
    container_name: parabankv2
    hostname: parabankv2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
<<<<<<< HEAD
      - 8091:8080
      - 9004:9001
      - 61617:61616
=======
      - 8091:8080 # HTTP
      - 9004:9001 # HSQLDB
      - 61617:61616 # JMS
>>>>>>> 21c951f (updates)
  demo-app:
    image: parasoft/demo-app:latest
    restart: unless-stopped
    container_name: demo-app
    hostname: demo-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
      - 4040:8080 # HTTP
      - 9003:9001 # HSQLDB
      - 50051:50051 # Rabbit MQ
      - 61623:61623 # Broker 1
      - 61624:62624 # Broker 2
      - 61626:61626 # Broker 3
  ltc:
    build: ltc
    restart: unless-stopped
    container_name: ltc
    hostname: ltc
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo-net
    ports:
      - 7080:8080 # HTTP
    #environment:
    #  CATALINA_OPTS: "${CATALINA_OPTS} -Duser.country=US -Duser.language=en"
    volumes:
      - type: bind
        source: ltc/data
        target: /usr/local/tomcat/data
    #  - type: bind
    #    source: ltc/web.xml
    #    target: /usr/local/tomcat/webapps/ltc/WEB-INF/web.xml
networks:
  demo-net:
    external: true
    name: demo-net