version: "3.9"
services:
  ctp:
    image: parasoft/ctp:2023.1
    hostname: ctp
    container_name: ctp
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 8080:8080
    environment:
      ACCEPT_EULA: true
      LICENSE_SERVER_URL: "${ls_url}"
      LICENSE_SERVER_AUTH_ENABLED: true
      LICENSE_SERVER_USERNAME: "${ls_user}"
      LICENSE_SERVER_PASSWORD: "${ls_pass}"
      USAGE_DATA: false
    volumes:
      - type: volume
        source: hsqldb
        target: /usr/local/parasoft/ctp/hsqldb
      - type: volume
        source: exports
        target: /usr/local/parasoft/exports
  soavirt-server:
    image: parasoft/soavirt-server:2023.1
    container_name: soavirt-server
    hostname: soavirt-server
    depends_on:
      - ctp
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 9080:9080
      - 9617:9617
      - 9618:9618
      - 9090-9099:9090-9099
    environment:
      ACCEPT_EULA: "true"
      HTTP_PORT: 9080
      EVENTS_PORT: 9617
      STATISTICS_PORT: 9618
    volumes:
      - type: volume
        source: workspace
        target: /usr/local/parasoft/soavirt/webapps/ROOT/workspace
      - type: bind
        source: ./soavirt/config.properties
        target: /usr/local/parasoft/soavirt/webapps/ROOT/WEB-INF/config.properties
  datarepo:
    image: parasoft/datarepo:3.6.1
    container_name: datarepo
    hostname: datarepo
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - "2424:2424"
    environment:
      USERNAME: ${dr_user}
      PASSWORD: ${dr_pass}
      CTP_URL: ${ctp_url}
      CTP_USERNAME: ${ctp_user}
      CTP_PASSWORD: ${ctp_pass}
      ALIAS: ${dr_alias}
    volumes:
      - type: bind
        source: ./datarepo/repositories
        target: /usr/local/parasoft/datarepo/repositories
  parabank:
    image: parasoft/parabank
    container_name: parabank
    hostname: parabank
    user: 0:0
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 8090:8080
      - 9001:9001
      - 61616:61616
      - 8050:8050
    env_file:
      - ./parabank/catalina.env
    volumes:
      - type: bind
        source: ./parabank/jdbc/jdbc.properties
        target: /usr/local/tomcat/webapps/parabank/WEB-INF/classes/jdbc.properties
      - type: bind
        source: ./parabank/jdbc/ParasoftJDBCDriver.jar
        target: /usr/local/tomcat/webapps/parabank/WEB-INF/lib/ParasoftJDBCDriver.jar
      - type: bind
        source: ./parabank/monitor
        target: /home/docker/jtest/monitor
  parabankv2:
    image: parasoft/parabank:feature
    container_name: parabankv2
    hostname: parabankv2
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 8091:8080
      - 9002:9001
      - 61617:61616
  demo-app:
    image: parasoft/demo-app
    container_name: demo-app
    hostname: demo-app
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 4040:8080
      - 9003:9001
      - 50051:50051
      - 61623:61623
      - 61624:62624
      - 61626:61626
  cam:
    build: ./cam
    image: parasoft/cam:latest
    container_name: cam
    hostname: cam
    extra_hosts:
      - "host.internal.docker:host-gateway"
    networks:
      - demo-net
    ports:
      - 6080:8080
volumes:
  hsqldb:
    external: true
    name: hsqldb
  exports:
    external: true
    name: exports
  workspace:
    external: true
    name: workspace
  parabank:
    external: true
    name: parabank
networks:
  demo-net:
    external: true
    name: demo-net